# Generated by Django 4.0.1 on 2022-01-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='appli_citizen',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='appli_religion',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='appli_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
