# Generated by Django 4.0.1 on 2022-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0004_alter_applicant_appli_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='appli_birthday',
            field=models.DateField(blank=True),
        ),
    ]
