# Generated by Django 4.0.1 on 2022-01-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0007_alter_applicant_appli_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='appli_emailaddress',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='appli_strand',
            field=models.CharField(choices=[('STEM', 'Science, Technology, Engineering, and Mathematics'), ('ABM', 'Accountancy, Business, and Management'), ('HUMSS', 'Humanities and Social Sciences'), ('TECH-VOC', 'Technical-Vocational-Livelihood'), ('GAS', 'General Academic Strand')], max_length=100),
        ),
    ]
