# Generated by Django 4.0.1 on 2022-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0009_applicant_appli_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.EmailField(default='emailadd', max_length=254),
        ),
    ]
