# Generated by Django 4.0.1 on 2022-01-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0010_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
