# Generated by Django 4.0.1 on 2022-01-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0011_alter_user_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
    ]
