# Generated by Django 4.0.1 on 2022-01-31 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0012_remove_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='appli_course',
            field=models.CharField(choices=[('BGT-AT', 'Bachelor in Graphics Technology major in Architecture Technology'), ('BET-ET', 'Bachelor of Engineering Technology major in Electrical Technology'), ('BET-ESET', 'Bachelor of Engineering Technology major in Electronics Technology'), ('BET-COET', 'Bachelor of Engineering Technology major in Computer Engineering Technology'), ('BET-CT', 'Bachelor of Engineering Technology major in Civil Technology'), ('BET-MT', 'Bachelor of Engineering Technology major in Mechanical Technology'), ('BET-AT', 'Bachelor of Engineering Technology major in Automotive Technology'), ('BET-PPT', 'Bachelor of Engineering Technology major in Power Plant Technology'), ('BSIE-IA', 'Bachelor of Science in Industrial Education major in Industrial Arts'), ('BSIE-ICT', 'Bachelor of Science in Industrial Education major in Information and Communication Technology'), ('BSCE', 'Bachelor of Science in Civil Engineering'), ('BSEE', 'Bachelor of Science in Electrical Engineering'), ('BSME', 'Bachelor of Science in Mechanical Engineering')], max_length=100),
        ),
        migrations.CreateModel(
            name='Applicant_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=10)),
                ('card', models.BooleanField(default=False)),
                ('barangay_clearance', models.BooleanField(default=False)),
                ('good_moral', models.BooleanField(default=False)),
                ('psa_birthcert', models.BooleanField(default=False)),
                ('medical_status', models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed')], max_length=100)),
                ('inter_status', models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed')], max_length=100)),
                ('user_appli', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissionApp.applicant')),
            ],
        ),
    ]
