# Generated by Django 4.0.1 on 2022-02-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0013_alter_applicant_appli_course_applicant_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tupadmin',
            name='user',
        ),
        migrations.DeleteModel(
            name='interviewer',
        ),
        migrations.DeleteModel(
            name='nurse',
        ),
        migrations.DeleteModel(
            name='tupadmin',
        ),
    ]
