# Generated by Django 4.0.1 on 2022-02-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0015_chatmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
