# Generated by Django 4.0.1 on 2022-02-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0016_applicant_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
    ]
