# Generated by Django 4.0.1 on 2022-02-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0017_alter_applicant_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_requirements',
            name='main_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='On Going', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant_requirements',
            name='inter_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='On Going', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant_requirements',
            name='medical_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='On Going', max_length=100),
        ),
    ]
