# Generated by Django 4.0.1 on 2022-02-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0018_applicant_requirements_main_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(max_length=20)),
                ('prepared_by', models.CharField(max_length=50)),
                ('examiner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissionApp.applicant')),
            ],
        ),
    ]
