# Generated by Django 4.0.1 on 2022-02-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0019_examschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='prepared_by',
        ),
    ]
