# Generated by Django 4.0.1 on 2022-03-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0021_thread_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_requirements',
            name='inter_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='On Going', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant_requirements',
            name='main_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='On Going', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant_requirements',
            name='medical_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='On Going', max_length=100),
        ),
        migrations.DeleteModel(
            name='chatMessages',
        ),
    ]
