# Generated by Django 4.0.1 on 2022-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0022_alter_applicant_requirements_inter_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_requirements',
            name='inter_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant_requirements',
            name='main_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant_requirements',
            name='medical_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
